name: Build and Deploy to Vercel (CI)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel@28

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          # Ensure VERCEL_TOKEN is present; vercel CLI will error otherwise
          if [ -z "${VERCEL_TOKEN}" ]; then
            echo "Missing VERCEL_TOKEN secret. Please add it in repository Settings -> Secrets" && exit 1
          fi
          # deploy the built output directory (dist) as a production deployment
          vercel --prod --token "$VERCEL_TOKEN" --confirm --yes
